-- ═══════════════════════════════════════════════════════════════
-- RACHA STATS — Schema do Supabase (SQL Editor)
-- Copie e cole este script no SQL Editor do seu projeto Supabase
-- ═══════════════════════════════════════════════════════════════

-- 1. Tabela de Jogadores
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  nickname TEXT,
  photo_url TEXT,
  position TEXT,
  user_id UUID UNIQUE -- Vincula ao auth.users do Supabase
);

-- 2. Tabela de Partidas
CREATE TABLE IF NOT EXISTS matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  location TEXT,
  team_a_name TEXT NOT NULL DEFAULT 'Time A',
  team_a_color TEXT NOT NULL DEFAULT '#2ecc40',
  team_b_name TEXT NOT NULL DEFAULT 'Time B',
  team_b_color TEXT NOT NULL DEFAULT '#ff4444',
  score_a INT NOT NULL DEFAULT 0,
  score_b INT NOT NULL DEFAULT 0,
  ai_summary TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Tabela de Escalações (Lineups)
CREATE TABLE IF NOT EXISTS lineups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE NOT NULL,
  player_id BIGINT REFERENCES players(id) ON DELETE CASCADE NOT NULL,
  team CHAR(1) NOT NULL CHECK (team IN ('A', 'B')),
  UNIQUE (match_id, player_id)
);

-- 4. Tabela de Gols
CREATE TABLE IF NOT EXISTS goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE NOT NULL,
  scorer_id BIGINT REFERENCES players(id) ON DELETE CASCADE NOT NULL,
  assist_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  team CHAR(1) NOT NULL CHECK (team IN ('A', 'B'))
);

-- 5. Tabela de Restrições (Duplas proibidas)
CREATE TABLE IF NOT EXISTS restrictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_a_id BIGINT REFERENCES players(id) ON DELETE CASCADE NOT NULL,
  player_b_id BIGINT REFERENCES players(id) ON DELETE CASCADE NOT NULL,
  description TEXT,
  UNIQUE (player_a_id, player_b_id)
);

-- 6. Tabela de Configurações do Sistema
CREATE TABLE IF NOT EXISTS config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Habilitar acesso a todas as tabelas (sem políticas restritivas complexas por enquanto para facilitar)
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE lineups ENABLE ROW LEVEL SECURITY;
ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE restrictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;

-- Políticas de acesso públicas (Leitura liberada para todos)
CREATE POLICY "Leitura pública players" ON players FOR SELECT USING (true);
CREATE POLICY "Leitura pública matches" ON matches FOR SELECT USING (true);
CREATE POLICY "Leitura pública lineups" ON lineups FOR SELECT USING (true);
CREATE POLICY "Leitura pública goals" ON goals FOR SELECT USING (true);
CREATE POLICY "Leitura pública restrictions" ON restrictions FOR SELECT USING (true);
CREATE POLICY "Leitura pública config" ON config FOR SELECT USING (true);

-- Permissões de escrita (Qualquer usuário autenticado pode cadastrar partidas/gols)
CREATE POLICY "Escrita autenticada matches" ON matches FOR ALL TO authenticated USING (true);
CREATE POLICY "Escrita autenticada lineups" ON lineups FOR ALL TO authenticated USING (true);
CREATE POLICY "Escrita autenticada goals" ON goals FOR ALL TO authenticated USING (true);

-- Controle específico de jogador: Usuários podem criar e atualizar seus próprios perfis
CREATE POLICY "Inserir players" ON players FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Atualizar próprio player" ON players FOR UPDATE TO authenticated USING (
  -- Permite se for o próprio usuário vinculado ou se for Admin
  auth.uid() = user_id OR auth.email() = 'nikolas@example.com' -- Admin fallback (mude para seu e-mail do Supabase)
);

-- Admin apenas (restrictions e config)
CREATE POLICY "Admin config" ON config FOR ALL TO authenticated USING (
  auth.email() = 'nikolas@example.com'
);
CREATE POLICY "Admin restrictions" ON restrictions FOR ALL TO authenticated USING (
  auth.email() = 'nikolas@example.com'
);
CREATE POLICY "Admin players delete" ON players FOR DELETE TO authenticated USING (
  auth.email() = 'nikolas@example.com'
);
